version: '3.4'

services:
  api:
    image: warre
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - /etc/warre:/etc/warre
  worker:
    image: warre
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /etc/warre:/etc/warre
    command: ["warre-worker"]