"""Initial migration.

Revision ID: 147fc7ff582d
Revises: 
Create Date: 2021-03-03 15:58:15.994150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147fc7ff582d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavor',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('vcpu', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('flavor_id', sa.String(length=64), nullable=False),
    sa.Column('lease_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('flavor')
    # ### end Alembic commands ###
