"""Add compute flavor to reservation

Revision ID: 26497add4de7
Revises: 43d884ebc331
Create Date: 2022-05-31 13:53:12.850123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26497add4de7'
down_revision = '43d884ebc331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('compute_flavor', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'compute_flavor')
    # ### end Alembic commands ###
