#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add ephemeral_gb to flavor

Revision ID: 2de2c31ac6e2
Revises: befa896143d5
Create Date: 2022-07-26 17:49:40.746699

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2de2c31ac6e2"
down_revision = "befa896143d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flavor", sa.Column("ephemeral_gb", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flavor", "ephemeral_gb")
    # ### end Alembic commands ###
