"""Add ephemeral_gb to flavor

Revision ID: 2de2c31ac6e2
Revises: befa896143d5
Create Date: 2022-07-26 17:49:40.746699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de2c31ac6e2'
down_revision = 'befa896143d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavor', sa.Column('ephemeral_gb', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavor', 'ephemeral_gb')
    # ### end Alembic commands ###
