"""Add flavor start and end

Revision ID: 35ef7858714d
Revises: 56280d4f9db9
Create Date: 2021-05-26 07:38:23.445242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ef7858714d'
down_revision = '56280d4f9db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavor', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('flavor', sa.Column('start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavor', 'start')
    op.drop_column('flavor', 'end')
    # ### end Alembic commands ###
