"""add instance count to reservation

Revision ID: 40707202a51b
Revises: 35ef7858714d
Create Date: 2021-07-28 12:50:09.247494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40707202a51b'
down_revision = '35ef7858714d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('instance_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'instance_count')
    # ### end Alembic commands ###
