"""Add zone and category to flavor

Revision ID: 43d884ebc331
Revises: b4a78f028f92
Create Date: 2022-05-27 13:27:04.210655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d884ebc331'
down_revision = 'b4a78f028f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavor', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('flavor', sa.Column('availability_zone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavor', 'availability_zone')
    op.drop_column('flavor', 'category')
    # ### end Alembic commands ###
