"""Add status_reason to reservation

Revision ID: b4a78f028f92
Revises: 40707202a51b
Create Date: 2021-07-29 12:37:22.717451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a78f028f92'
down_revision = '40707202a51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('status_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'status_reason')
    # ### end Alembic commands ###
