"""Add extra-specs to reservation

Revision ID: f08f1d5a7dfa
Revises: 6821e37ce4e2
Create Date: 2021-04-07 17:57:30.003513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08f1d5a7dfa'
down_revision = '6821e37ce4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavor', sa.Column('extra_specs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavor', 'extra_specs')
    # ### end Alembic commands ###
